# Setup
title:               SubbulakshmiRS
tagline:             'Wild & Free'
description:         'Personal website for my whimsies'
url:                 https://subbulakshmirs.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              R S Subbulakshmi
  url:               https://github.com/SubbulakshmiRS
  email:             rssubbulakshmi16@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
